os:
  - linux
language: python
python:
  - 3.5
before_install:
  - sudo apt-get install ruby ruby-dev build-essential
  - sudo gem install --no-ri --no-rdoc fpm
install:
  - pip install -r requirements.txt
script:
  - fbs freeze
  - fbs installer
