name: Package with Github Actions
run-name: ${{ github.actor }} is packaging on Github Actions
on: [push]
jobs:
  build-macos:
    runs-on: macos-11
    strategy:
      matrix:
        python-version: ["3.6"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt
      - name: Package app with fbs
        run: |
          fbs freeze
      - name: Package installer with fbs
        run: |
          fbs installer
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: gemino-macOS
          path: target/gemino.dmg
  build-ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.6"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt
      - name: Package app with fbs
        run: |
          fbs freeze
      - name: Package installer with fbs
        run: |
          fbs installer
      - name: List target files
        run: |
          ls -lah target
  build-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ["3.6"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt
      - name: Package app with fbs
        run: |
          fbs freeze
      - name: Package installer with fbs
        run: |
          fbs installer
      - name: List target files
        run: |
          dir target